# Generated by Django 3.1.4 on 2021-02-01 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EVCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_category', models.CharField(max_length=200)),
                ('category_summary', models.CharField(max_length=200)),
                ('category_slug', models.CharField(default=1, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='EVInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_title', models.CharField(max_length=100)),
                ('ev_image', models.ImageField(upload_to='gallery')),
                ('ev_emi', models.CharField(max_length=100)),
                ('ev_country', models.CharField(max_length=100)),
                ('ev_summary', models.CharField(max_length=200)),
                ('ev_slug', models.CharField(default=1, max_length=200)),
                ('ev_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.evcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Information',
            },
        ),
    ]
