# Generated by Django 3.1.4 on 2021-02-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsAndCustomize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
                ('color', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.AddField(
            model_name='evinformation',
            name='ev_high',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
