# Generated by Django 3.1.4 on 2021-02-01 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210202_0031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelsAndCustomize',
        ),
        migrations.RemoveField(
            model_name='evinformation',
            name='ev_high',
        ),
    ]
