# Generated by Django 3.1.4 on 2021-02-01 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210202_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsAndCustomize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_model1', models.CharField(max_length=100)),
                ('ev_model2', models.CharField(max_length=100)),
                ('ev_color1', models.ImageField(upload_to='gallery')),
                ('ev_color2', models.ImageField(upload_to='gallery')),
                ('ev_title', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.evinformation', verbose_name='Information')),
            ],
            options={
                'verbose_name_plural': 'Customization',
            },
        ),
        migrations.CreateModel(
            name='EVHighlights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_high1', models.CharField(max_length=100)),
                ('ev_high2', models.CharField(max_length=100)),
                ('ev_high3', models.CharField(max_length=100)),
                ('ev_high4', models.CharField(max_length=100)),
                ('ev_high5', models.CharField(max_length=100)),
                ('ev_title', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.evinformation', verbose_name='Information')),
            ],
            options={
                'verbose_name_plural': 'Highlights',
            },
        ),
    ]
