# Generated by Django 3.1.4 on 2021-02-01 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_evhighlights_modelsandcustomize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelsAndCustomize',
        ),
    ]
