# Generated by Django 3.1.4 on 2021-02-01 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_modelsandcustomize'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_model', models.CharField(default='No models', max_length=100)),
                ('ev_model_city', models.IntegerField()),
                ('ev_model_hwy', models.IntegerField()),
                ('ev_model_mix', models.IntegerField()),
                ('ev_title', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.evinformation', verbose_name='Information')),
            ],
            options={
                'verbose_name_plural': 'Customization',
            },
        ),
        migrations.DeleteModel(
            name='ModelsAndCustomize',
        ),
    ]
