# Generated by Django 3.1.4 on 2021-02-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210202_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evhighlights',
            name='ev_high5',
        ),
    ]
