# Generated by Django 3.1.4 on 2021-02-02 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_evhighlights_ev_high5'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVColorCustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_color', models.ImageField(upload_to='gallery')),
                ('ev_title', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.evinformation', verbose_name='Information')),
            ],
        ),
    ]
